<?php

namespace App\Services;

use App\Models\Loan;
use App\Models\LoanApplication;
use App\Models\LoanProduct;
use App\Models\Payment;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

/**
 * Centralized SOA builder.
 *
 * - Builds an official, product-specific amortization schedule + fee breakdown using `LoanCalculator`.
 * - Syncs legacy `loan.schedule_json` + `loan.payments` when the SOA snapshot/engine version is missing.
 * - Keeps payment history data (`amount_paid`, `paid_at`, `receipt` fields) while updating scheduled amounts
 *   to ensure the printed statement is financially consistent.
 */
class LoanStatementOfAccountService
{
    private const ENGINE_VERSION = 'soa_v2';

    public function __construct(
        private LoanCalculator $calculator,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function build(Loan $loan): array
    {
        $loan->loadMissing(['borrower', 'approver', 'loanApplication', 'payments']);

        $payload = is_array($loan->application_payload) ? $loan->application_payload : [];
        $snapshot = Arr::get($payload, 'soa_snapshot');
        $engineVersion = (string) Arr::get($payload, 'soa_engine_version');

        // For legacy loans, keep a consistent SOA even if the stored schedule/payments were generated by old formulas.
        if (! is_array($snapshot) || $engineVersion !== self::ENGINE_VERSION) {
            $this->syncLoanToEngine($loan);
            $loan->refresh();
            $payload = is_array($loan->application_payload) ? $loan->application_payload : [];
            $snapshot = Arr::get($payload, 'soa_snapshot');
        }

        $snapshot = is_array($snapshot) ? $snapshot : [];
        $breakdown = is_array($snapshot['breakdown'] ?? null) ? $snapshot['breakdown'] : [];
        $product = is_array($snapshot['product'] ?? null) ? $snapshot['product'] : [];

        $schedule = is_array($loan->schedule_json) ? $loan->schedule_json : [];
        $paymentsBy = ($loan->payments ?? collect())->keyBy(fn (Payment $p) => (int) $p->installment_no);

        // Totals use system payment ledger (amount_due + penalty_amount) minus amount_paid.
        $totalDueWithPenalties = 0.0;
        $totalPaid = 0.0;
        foreach ($schedule as $row) {
            $no = (int) ($row['installment_no'] ?? 0);
            $p = $paymentsBy->get($no);
            $due = isset($p) ? (float) ($p->amount_due ?? 0) : (float) ($row['payment'] ?? 0);
            $pen = isset($p) ? (float) ($p->penalty_amount ?? 0) : 0.0;
            $totalDueWithPenalties += $due + $pen;
        }
        foreach ($paymentsBy as $p) {
            $totalPaid += (float) ($p->amount_paid ?? 0);
        }
        $remainingBalance = max(0.0, round($totalDueWithPenalties - $totalPaid, 2));

        // Running balance per installment: due (incl. penalties) remaining after cumulative paid through that installment.
        $cumPaid = 0.0;
        $rows = [];
        foreach ($schedule as $row) {
            $no = (int) ($row['installment_no'] ?? 0);
            $p = $paymentsBy->get($no);

            $amountPaid = (float) ($p?->amount_paid ?? 0);
            $penalty = (float) ($p?->penalty_amount ?? 0);
            $due = (float) ($p?->amount_due ?? ($row['payment'] ?? 0));

            $cumPaid += $amountPaid;
            $runningBalance = max(0.0, round($totalDueWithPenalties - $cumPaid, 2));

            $rows[] = [
                'installment_no' => $no,
                'due_date' => $row['due_date'] ?? null,
                'payment_due' => $due,
                'principal' => (float) ($row['principal'] ?? 0),
                'interest' => (float) ($row['interest'] ?? 0),
                'amortization' => (float) ($row['amortization'] ?? ($row['payment'] ?? 0)),
                'balance' => (float) ($row['balance'] ?? 0),
                'penalty_amount' => $penalty,
                'amount_paid' => $amountPaid,
                'pay_status' => $p?->status ?? '—',
                'running_balance' => $runningBalance,
            ];
        }

        return [
            'engine_version' => self::ENGINE_VERSION,
            'snapshot' => $snapshot,
            'product' => $product,
            'breakdown' => $breakdown,
            'loan' => $loan,
            'borrower' => $loan->borrower,
            'schedule_rows' => $rows,
            'totals' => [
                'total_due_with_penalties' => round($totalDueWithPenalties, 2),
                'total_paid' => round($totalPaid, 2),
                'remaining_balance' => $remainingBalance,
            ],
            'approval' => [
                'approved_at' => $loan->approved_at?->toIso8601String(),
                'approved_by' => $loan->approved_by
                    ? (string) ($loan->approver?->username ?? $loan->approver?->name ?? (string) $loan->approved_by)
                    : null,
            ],
        ];
    }

    private function syncLoanToEngine(Loan $loan): void
    {
        $payload = is_array($loan->application_payload) ? $loan->application_payload : [];

        $productSlug = $payload['loan_product_slug'] ?? null;
        $application = $loan->loanApplication;
        if (! is_string($productSlug) || trim($productSlug) === '') {
            $productSlug = $this->inferProductSlugFromLoanApplication($application);
        }

        if (! is_string($productSlug) || trim($productSlug) === '') {
            // Legacy continuity: if `loanApplication` does not exist either, infer from monthly interest rate.
            $monthlyRateGuess = (float) ($loan->annual_interest_rate / 12.0);
            $candidate = LoanProduct::query()
                ->active()
                ->where('rate_type', 'monthly')
                ->get()
                ->first(function (LoanProduct $p) use ($monthlyRateGuess) {
                    return abs((float) $p->interest_rate - $monthlyRateGuess) < 0.0001;
                });

            $productSlug = $candidate?->slug;
        }

        if (! is_string($productSlug) || trim($productSlug) === '') {
            // No product slug: cannot generate product-specific SOA fees.
            return;
        }

        $applicationNature = (string) ($payload['application_nature'] ?? 'new');
        $age = Arr::get($payload, 'age');
        if ($age === null && $application) {
            $age = $application->age;
        }

        $monthlyPension = Arr::get($payload, 'monthly_pension');
        if ($monthlyPension === null && $application) {
            $monthlyPension = $application->monthly_pension;
        }
        $pensionType = Arr::get($payload, 'pension_type');
        if (($pensionType === null || $pensionType === '') && $application) {
            $pensionType = $application->pension_type;
        }

        $compute = $this->calculator->compute([
            'product_slug' => (string) $productSlug,
            'loan_amount' => (float) $loan->principal,
            'term_months' => (int) $loan->term_months,
            'application_nature' => $applicationNature,
            'age' => $age !== null && $age !== '' ? (int) $age : null,
            'monthly_pension' => $monthlyPension !== null && $monthlyPension !== '' ? (float) $monthlyPension : null,
            'pension_type' => $pensionType !== null && $pensionType !== '' ? (string) $pensionType : null,
        ]);

        DB::transaction(function () use ($loan, $payload, $compute) {
            $product = is_array($compute['product'] ?? null) ? $compute['product'] : [];
            $breakdown = is_array($compute['breakdown'] ?? null) ? $compute['breakdown'] : [];
            $schedule = is_array($compute['schedule'] ?? null) ? $compute['schedule'] : [];

            // Persist SOA snapshot for historical accuracy.
            $payload = is_array($loan->application_payload) ? $loan->application_payload : [];
            $payload['loan_product_slug'] = $payload['loan_product_slug'] ?? (string) ($product['slug'] ?? '');
            $payload['soa_engine_version'] = self::ENGINE_VERSION;
            $payload['soa_snapshot'] = [
                'product' => $product,
                'inputs' => is_array($compute['inputs'] ?? null) ? $compute['inputs'] : [],
                'breakdown' => $breakdown,
                'summary' => is_array($compute['summary'] ?? null) ? $compute['summary'] : [],
                'notes' => is_array($compute['notes'] ?? null) ? $compute['notes'] : [],
                'generated_at' => now()->toIso8601String(),
            ];
            $loan->application_payload = $payload;

            $monthlyRate = isset($product['monthly_rate_percent_effective']) ? (float) $product['monthly_rate_percent_effective'] : null;
            if ($monthlyRate !== null) {
                $loan->annual_interest_rate = round($monthlyRate * 12.0, 4);
            }

            $loan->monthly_payment = isset($breakdown['monthly_amortization']) ? (float) $breakdown['monthly_amortization'] : $loan->monthly_payment;
            $loan->total_interest = isset($breakdown['total_add_on_interest']) ? (float) $breakdown['total_add_on_interest'] : $loan->total_interest;
            $loan->schedule_json = $schedule;

            // Update/create payment ledger rows while keeping historical payment receipts + amounts.
            $existingPayments = $loan->payments()->get()->keyBy(fn (Payment $p) => (int) $p->installment_no);
            $term = (int) $loan->term_months;

            $scheduleByNo = [];
            foreach ($schedule as $r) {
                $scheduleByNo[(int) ($r['installment_no'] ?? 0)] = $r;
            }

            for ($i = 1; $i <= max(1, $term); $i++) {
                $r = $scheduleByNo[$i] ?? null;
                if (! is_array($r)) {
                    continue;
                }
                $dueDate = $r['due_date'] ?? null;
                $amountDue = isset($r['payment']) ? (float) $r['payment'] : ((float) ($r['amortization'] ?? 0));
                $principalPortion = (float) ($r['principal'] ?? 0);
                $interestPortion = (float) ($r['interest'] ?? 0);

                $p = $existingPayments->get($i);
                if ($p) {
                    $p->due_date = $dueDate ? (string) $dueDate : $p->due_date;
                    $p->amount_due = round($amountDue, 2);
                    $p->principal_portion = round($principalPortion, 2);
                    $p->interest_portion = round($interestPortion, 2);
                    // Keep amount_paid, paid_at, penalty_amount, receipt refs, etc.
                    $p->save();
                } else {
                    Payment::create([
                        'loan_id' => $loan->id,
                        'installment_no' => $i,
                        'due_date' => $dueDate,
                        'amount_due' => round($amountDue, 2),
                        'principal_portion' => round($principalPortion, 2),
                        'interest_portion' => round($interestPortion, 2),
                        'status' => Payment::STATUS_PENDING,
                        'source' => 'system',
                        'penalty_amount' => 0.0,
                    ]);
                }
            }

            // Recompute payment statuses based on updated schedule + stored amount_paid.
            $payments = $loan->payments()->get();
            foreach ($payments as $p) {
                $due = (float) ($p->amount_due ?? 0);
                $paid = (float) ($p->amount_paid ?? 0);
                if ($due <= 0) {
                    $p->status = Payment::STATUS_PENDING;
                } elseif ($paid >= $due - 0.01) {
                    $p->status = Payment::STATUS_PAID;
                    $p->paid_at = $p->paid_at ?? now();
                    $p->amount_paid = round($paid, 2);
                } elseif ($paid > 0) {
                    $p->status = Payment::STATUS_PARTIAL;
                } else {
                    $p->status = Payment::STATUS_PENDING;
                }

                if ($p->status !== Payment::STATUS_PAID && $p->due_date && $p->due_date->isPast()) {
                    $p->status = Payment::STATUS_OVERDUE;
                }
                $p->save();
            }

            // Refresh loan outstanding balance (system definition: amount_due - amount_paid, ignoring penalties).
            $summary = Payment::query()
                ->where('loan_id', $loan->id)
                ->selectRaw('COALESCE(SUM(GREATEST(amount_due - amount_paid, 0)), 0) AS remaining_balance')
                ->first();
            $loan->outstanding_balance = round((float) ($summary->remaining_balance ?? 0), 2);

            if ($loan->status === Loan::STATUS_ONGOING) {
                $unpaidCount = (int) Payment::query()
                    ->where('loan_id', $loan->id)
                    ->where('status', '!=', Payment::STATUS_PAID)
                    ->count();

                if ($unpaidCount === 0) {
                    $loan->status = Loan::STATUS_COMPLETED;
                    $loan->completed_at = $loan->completed_at ?? now();
                }
            }

            $loan->save();
        });
    }

    private function inferProductSlugFromLoanApplication(?LoanApplication $application): ?string
    {
        if (! $application) {
            return null;
        }

        return match ($application->loan_type) {
            LoanApplication::TYPE_REAL_ESTATE => 'real-estate-mortgage',
            LoanApplication::TYPE_CHATTEL => 'chattel-mortgage',
            LoanApplication::TYPE_SALARY => 'salary-loan',
            LoanApplication::TYPE_TRAVEL_ASSISTANCE => 'travel-assistance-loan',
            LoanApplication::TYPE_SSS_PENSION => 'sss-pension-loan',
            default => null,
        };
    }
}
