<?php

namespace Database\Seeders;

use App\Models\LoanProduct;
use Illuminate\Database\Seeder;

class LoanProductSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'slug' => 'real-estate-mortgage',
                'code' => 'REM',
                'name' => 'REM (Real Estate Mortgage)',
                'description' => 'Long-term financing secured by real property title.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'Title',
                'collateral_type' => 'Real Property Title',
                'requirements' => 'Valid title, proof of income, appraisal.',
                'max_term' => 36,
                'max_amount' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'blue',
                'icon_key' => 'home',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => [
                    'fee_profile' => 'mortgage',
                    'computation_style' => 'straight_line',
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 1500,
                    'notarial_fee_reloan' => 1500,
                    'mortgage_fee_rate' => 0.025,
                    'mortgage_fee_threshold' => 200000,
                ],
                'sort_order' => 10,
            ],
            [
                'slug' => 'chattel-mortgage',
                'code' => 'CHM',
                'name' => 'CHM (Chattel Mortgage)',
                'description' => 'Vehicle and movable asset financing.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'OR/CR',
                'collateral_type' => 'Vehicle OR/CR',
                'requirements' => 'Vehicle documents, insurance.',
                'max_term' => 36,
                'max_amount' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'blue',
                'icon_key' => 'vehicle',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => [
                    'fee_profile' => 'mortgage',
                    'computation_style' => 'straight_line',
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 1500,
                    'notarial_fee_reloan' => 1500,
                    'mortgage_fee_rate' => 0.025,
                    'mortgage_fee_threshold' => 200000,
                ],
                'sort_order' => 20,
            ],
            [
                'slug' => 'salary-loan',
                'code' => 'SAL',
                'name' => 'Salary Loan (Employees ACI)',
                'description' => 'Payroll-based lending for ACI employees.',
                'interest_rate' => 1.5,
                'rate_type' => 'monthly',
                'collateral' => 'Salary Deduction',
                'collateral_type' => 'Salary Assignment',
                'requirements' => 'Employment certificate, payroll enrollment.',
                'max_term' => 60,
                'max_amount' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'green',
                'icon_key' => 'briefcase',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => [
                    'salary_principal_multiplier' => 6,
                    'fee_profile' => 'salary',
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 500,
                    'notarial_fee_reloan' => 500,
                    'mortgage_fee_rate' => 0,
                    'mortgage_fee_threshold' => 999999999,
                ],
                'sort_order' => 30,
            ],
            [
                'slug' => 'travel-assistance-loan',
                'code' => 'TRV',
                'name' => 'Travel Assistance (Work Abroad)',
                'description' => 'Support for documented overseas workers.',
                'interest_rate' => 3.5,
                'rate_type' => 'monthly',
                'collateral' => 'Landbank Account',
                'collateral_type' => 'Bank Account Holdout',
                'requirements' => 'Requirement: Landbank account, employment contract abroad.',
                'max_term' => 1,
                'max_amount' => 2000000,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'orange',
                'icon_key' => 'plane',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => [
                    'fixed_term_months' => 1,
                    'term_structure' => 'monthly_renewal',
                    'fee_profile' => 'travel',
                    'max_principal' => 2000000,
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 1000,
                    'notarial_fee_reloan' => 1000,
                    'mortgage_fee_rate' => 0,
                    'mortgage_fee_threshold' => 999999999,
                ],
                'sort_order' => 40,
            ],
            [
                'slug' => 'sss-pension-loan',
                'code' => 'PEN',
                'name' => 'SSS/GSIS (Pensioner Loan)',
                'description' => 'For pensioners with SSS or GSIS pension.',
                'interest_rate' => 2.24,
                'rate_type' => 'monthly',
                'collateral' => 'ATM Card',
                'collateral_type' => 'Pension ATM',
                'requirements' => 'Valid pension ID, ATM for collateral.',
                'max_term' => 36,
                'max_amount' => 1000000,
                'age_limit' => 70,
                'safe_age' => 65,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'green',
                'icon_key' => 'shield',
                'sample_monthly_pension' => 4000,
                'sample_computation_note' => 'Illustrative only; final amount subject to credit evaluation.',
                'calculator_config' => [
                    'pension_multiplier' => 18.75,
                    'max_principal' => 1000000,
                    'notarial_new_loan' => 350,
                    'insurance_per_1000' => 35,
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 350,
                    'notarial_fee_reloan' => 350,
                    'mortgage_fee_rate' => 0,
                    'mortgage_fee_threshold' => 999999999,
                ],
                'sort_order' => 50,
            ],
            [
                'slug' => 'appliance',
                'code' => 'APL',
                'name' => 'Appliance Loan',
                'description' => 'Retail financing for appliances and electronics.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'Retail partner hold-out',
                'collateral_type' => 'Retail Item',
                'requirements' => 'Valid ID, proof of address.',
                'max_term' => 24,
                'max_amount' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => '15% of SRP',
                'status' => 'active',
                'tier' => 'orange',
                'icon_key' => 'appliance',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => [
                    'fee_profile' => 'appliance',
                ],
                'rules' => [
                    'service_charge_rate' => 0.035,
                    'insurance_per_1000' => 35,
                    'insurance_fixed' => 2000,
                    'doc_stamp_rate_decimal' => 0.0075,
                    'notarial_fee_new' => 500,
                    'notarial_fee_reloan' => 500,
                    'mortgage_fee_rate' => 0,
                    'mortgage_fee_threshold' => 999999999,
                ],
                'sort_order' => 60,
            ],
        ];

        foreach ($rows as $row) {
            LoanProduct::updateOrCreate(['slug' => $row['slug']], $row);
        }
    }
}
