import { LOAN_PRODUCT_KEYS } from '../components/loan/loanProductDocuments.js'

/** @typedef {import('../components/loan/PublicLoanProductPage.jsx').PublicLoanProductConfig} PublicLoanProductConfig */

/** @type {Record<string, PublicLoanProductConfig>} */
export const PUBLIC_LOAN_PRODUCT_CONFIG = {
  'chattel-mortgage': {
    slug: 'chattel-mortgage',
    title: 'Chattel Mortgage Loan',
    iconKey: 'vehicle',
    tier: 'blue',
    fallbackRateLabel: '3.88% per month',
    interestRate: 3.88,
    interestRateLabel: '3.88% per month',
    loanAmountRange: 'PHP 50,000 - PHP 5,000,000',
    minAmount: 50000,
    maxAmount: 5000000,
    defaultAmount: 250000,
    loanTerms: '6 - 60 Months',
    minTerm: 6,
    maxTerm: 60,
    defaultTerm: 24,
    processingTime: '3 - 7 business days',
    description: 'Vehicle and movable asset financing secured by collateral.',
    infoItems: [
      { label: 'Interest rate', value: '3.88% per month' },
      { label: 'Loan amount', value: 'PHP 50,000 - PHP 5,000,000' },
      { label: 'Loan terms', value: '6 - 60 Months' },
      { label: 'Processing time', value: '3 - 7 business days' },
    ],
    benefits: ['Higher Loan Amount', 'Vehicle Financing', 'Flexible Repayment Terms'],
    features: [
      { title: 'Collateral-backed approval', body: 'Use qualified vehicles and movable assets as collateral for larger financing needs.' },
      { title: 'Asset purchase or refinancing', body: 'Supports vehicle financing, business mobility, and approved movable asset funding.' },
      { title: 'Flexible repayment terms', body: 'Choose a monthly term that fits your cash flow, subject to credit review.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.CHATTEL_MORTGAGE,
    eligibility: ['Vehicle Owner', 'Complete OR/CR', 'Proof of Income'],
    requiredDocuments: ['OR/CR', 'Vehicle Photos', 'Insurance Policy', 'Government ID'],
  },
  'real-estate-mortgage': {
    slug: 'real-estate-mortgage',
    title: 'Real Estate Mortgage Loan',
    iconKey: 'home',
    tier: 'purple',
    fallbackRateLabel: '3.88% per month',
    interestRate: 3.88,
    interestRateLabel: '3.88% per month',
    loanAmountRange: 'PHP 100,000 - PHP 20,000,000',
    minAmount: 100000,
    maxAmount: 20000000,
    defaultAmount: 1000000,
    loanTerms: '12 - 120 Months',
    minTerm: 12,
    maxTerm: 120,
    defaultTerm: 60,
    processingTime: '5 - 10 business days',
    description: 'Property-backed financing for residential, commercial, and agricultural properties.',
    infoItems: [
      { label: 'Interest rate', value: '3.88% per month' },
      { label: 'Loan amount', value: 'PHP 100,000 - PHP 20,000,000' },
      { label: 'Loan terms', value: '12 - 120 Months' },
      { label: 'Processing time', value: '5 - 10 business days' },
    ],
    benefits: ['High Loanable Amount', 'Longer Repayment Terms', 'Property-Based Approval'],
    features: [
      { title: 'Residential, commercial, or agricultural', body: 'Accepts qualified real property types after title and appraisal checks.' },
      { title: 'Longer repayment horizon', body: 'Structure repayment over longer terms for larger property-backed needs.' },
      { title: 'Branch-guided documentation', body: 'Loan officers guide title, tax, and appraisal requirements before approval.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.REAL_ESTATE_MORTGAGE,
    eligibility: ['Property Owner', 'Clean Land Title', 'Proof of Income'],
    requiredDocuments: ['Land Title', 'Tax Declaration', 'Tax Clearance', 'Property Photos', 'Valid ID'],
  },
  'salary-loan': {
    slug: 'salary-loan',
    title: 'Salary Loan',
    iconKey: 'briefcase',
    tier: 'green',
    fallbackRateLabel: '1.50% per month',
    interestRate: 1.5,
    interestRateLabel: '1.50% per month',
    loanAmountRange: 'PHP 10,000 - PHP 300,000',
    minAmount: 10000,
    maxAmount: 300000,
    defaultAmount: 50000,
    loanTerms: '3 - 36 Months',
    minTerm: 3,
    maxTerm: 36,
    defaultTerm: 12,
    processingTime: '1 - 3 business days',
    description: 'Payroll-backed financing for employed individuals with predictable income and qualified co-makers.',
    infoItems: [
      { label: 'Interest rate', value: '1.50% per month' },
      { label: 'Loan amount', value: 'PHP 10,000 - PHP 300,000' },
      { label: 'Loan terms', value: '3 - 36 Months' },
      { label: 'Processing time', value: '1 - 3 business days' },
    ],
    benefits: ['Low Interest Rate', 'Fast Approval', 'Flexible Payment Terms', 'Salary-Based Qualification'],
    features: [
      { title: 'Payroll-backed financing', body: 'Loan assessment is anchored on documented employment and predictable salary income.' },
      { title: 'Co-maker supported', body: 'Qualified co-makers can strengthen the application and support approval.' },
      { title: 'Convenient amortization', body: 'Monthly payment estimates help borrowers choose a practical term before applying.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.SALARY_LOAN,
    eligibility: ['Employed', 'At least 6 months employed', 'Stable income source', 'Valid Government ID'],
    requiredDocuments: ['Company ID', 'Payslip', 'Certificate of Employment', 'Valid Government ID', 'Selfie with ID'],
  },
  appliance: {
    slug: 'appliance-loan',
    applySlug: 'appliance',
    title: 'Appliance Loan',
    iconKey: 'appliance',
    tier: 'blue',
    fallbackRateLabel: '3.88% per month',
    interestRate: 3.88,
    interestRateLabel: '3.88% per month',
    loanAmountRange: 'PHP 5,000 - PHP 200,000',
    minAmount: 5000,
    maxAmount: 200000,
    defaultAmount: 25000,
    loanTerms: '3 - 24 Months',
    minTerm: 3,
    maxTerm: 24,
    defaultTerm: 12,
    processingTime: '1 - 3 business days',
    description: 'Affordable financing for appliances, electronics, gadgets, and approved partner stores.',
    infoItems: [
      { label: 'Interest rate', value: '3.88% per month' },
      { label: 'Loan amount', value: 'PHP 5,000 - PHP 200,000' },
      { label: 'Loan terms', value: '3 - 24 Months' },
      { label: 'Processing time', value: '1 - 3 business days' },
    ],
    benefits: ['Easy Approval', 'Partner Merchant Support', 'Flexible Terms'],
    features: [
      { title: 'Appliance and gadget financing', body: 'Finance qualified appliances, electronics, gadgets, and partner store purchases.' },
      { title: 'Partner merchant support', body: 'Use a quotation or invoice from approved merchants to support your application.' },
      { title: 'Short-term affordability', body: 'Choose compact terms that keep purchases manageable month to month.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.APPLIANCE_LOAN,
    eligibility: ['Valid Government ID', 'Proof of billing address', 'Proof of income', 'Approved purchase quotation or invoice'],
    requiredDocuments: ['Valid ID', 'Proof of Billing', 'Proof of Income', 'Quotation/Invoice'],
  },
  'travel-assistance-loan': {
    slug: 'travel-assistance-loan',
    title: 'Travel Assistance Loan',
    iconKey: 'plane',
    tier: 'orange',
    fallbackRateLabel: '3.50% per month',
    interestRate: 3.5,
    interestRateLabel: '3.50% per month',
    loanAmountRange: 'PHP 10,000 - PHP 500,000',
    minAmount: 10000,
    maxAmount: 500000,
    defaultAmount: 75000,
    loanTerms: '3 - 36 Months',
    minTerm: 3,
    maxTerm: 36,
    defaultTerm: 12,
    processingTime: '1 - 3 business days',
    description: 'Financial assistance for OFWs, seafarers, students, tourists, and professionals requiring travel-related funding.',
    infoItems: [
      { label: 'Interest rate', value: '3.50% per month' },
      { label: 'Loan amount', value: 'PHP 10,000 - PHP 500,000' },
      { label: 'Loan terms', value: '3 - 36 Months' },
      { label: 'Processing time', value: '1 - 3 business days' },
    ],
    benefits: ['OFW Friendly', 'Visa Processing Assistance', 'Travel Cost Financing', 'Fast Approval'],
    eligiblePurposes: ['OFW Deployment', 'Seafarer Deployment', 'Tourist Travel', 'Educational Travel', 'Medical Travel', 'Business Travel'],
    features: [
      { title: 'Deployment and travel support', body: 'Supports travel-related funding for employment, study, business, and medical purposes.' },
      { title: 'Borrower-friendly documents', body: 'Upload ID, income, and billing proof at application. Agency travel documents can be added later by staff.' },
      { title: 'Fast approval path', body: 'Designed for time-sensitive trips once your core documents are complete.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.TRAVEL_ASSISTANCE,
    eligibility: [
      'Qualified OFW, seafarer, student, tourist, professional, or traveler with a documented purpose',
      'Valid government ID and proof of income',
      'Proof of billing at your current address',
      'Travel cost breakdown for quotation reference',
      'Complete borrower portal application and document uploads',
    ],
    requiredDocuments: [
      'Valid Government ID',
      'Proof of Income',
      'Proof of Billing',
      'Certificate of Employment (if applicable)',
      'Passport (if available)',
    ],
  },
  'sss-pension-loan': {
    slug: 'sss-pension-loan',
    title: 'SSS Pension Loan',
    iconKey: 'shield',
    tier: 'green',
    fallbackRateLabel: '2.24% per month',
    interestRate: 2.24,
    interestRateLabel: '2.24% per month',
    loanAmountRange: 'PHP 10,000 - PHP 500,000',
    minAmount: 10000,
    maxAmount: 500000,
    defaultAmount: 50000,
    loanTerms: '6 - 36 Months',
    minTerm: 6,
    maxTerm: 36,
    defaultTerm: 12,
    processingTime: '1 - 3 business days',
    description: 'Dedicated financing for qualified SSS pensioners.',
    infoItems: [
      { label: 'Interest rate', value: '2.24% per month' },
      { label: 'Loan amount', value: 'PHP 10,000 - PHP 500,000' },
      { label: 'Loan terms', value: '6 - 36 Months' },
      { label: 'Processing time', value: '1 - 3 business days' },
    ],
    benefits: ['Pension-Based Qualification', 'Flexible Terms', 'Minimal Requirements'],
    features: [
      { title: 'Pension-based review', body: 'Eligibility is assessed using verified pension documents, proof of billing, and repayment capacity.' },
      { title: 'Operational document set', body: 'Prepare ACOP, Barangay Certificate, proof of billing, and valid government ID before applying.' },
      { title: 'Flexible payment terms', body: 'Select a term that aligns with your monthly pension flow.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.SSS_PENSION,
    eligibility: [
      'Active pensioner with verifiable SSS/GSIS benefits',
      'Latest ACOP and proof of current residence',
      'Proof of billing and valid government-issued ID',
      'Age within product safe limits',
    ],
    requiredDocuments: ['ACOP', 'Barangay Certificate', 'Proof of Billing', 'Valid Government ID'],
  },
  'gsis-pension-loan': {
    slug: 'gsis-pension-loan',
    applySlug: 'sss-pension-loan',
    title: 'GSIS Pension Loan',
    iconKey: 'shield',
    tier: 'green',
    fallbackRateLabel: '2.24% per month',
    interestRate: 2.24,
    interestRateLabel: '2.24% per month',
    loanAmountRange: 'PHP 10,000 - PHP 500,000',
    minAmount: 10000,
    maxAmount: 500000,
    defaultAmount: 50000,
    loanTerms: '6 - 36 Months',
    minTerm: 6,
    maxTerm: 36,
    defaultTerm: 12,
    processingTime: '1 - 3 business days',
    description: 'Dedicated financing for qualified GSIS retirees and pensioners.',
    infoItems: [
      { label: 'Interest rate', value: '2.24% per month' },
      { label: 'Loan amount', value: 'PHP 10,000 - PHP 500,000' },
      { label: 'Loan terms', value: '6 - 36 Months' },
      { label: 'Processing time', value: '1 - 3 business days' },
    ],
    benefits: ['Pension-Based Financing', 'Fast Processing', 'Flexible Payment Options'],
    features: [
      { title: 'GSIS pensioner support', body: 'Built for qualified GSIS retirees and pensioners with verifiable benefits.' },
      { title: 'Fast processing', body: 'Complete documents help speed up verification and approval review.' },
      { title: 'Flexible payment options', body: 'Select repayment terms that fit pension-based cash flow.' },
    ],
    productKey: LOAN_PRODUCT_KEYS.GSIS_PENSION,
    eligibility: ['Qualified GSIS retiree or pensioner', 'Latest ACOP and proof of residence', 'Proof of billing and valid government ID'],
    requiredDocuments: ['ACOP', 'Barangay Certificate', 'Proof of Billing', 'Valid Government ID'],
  },
}

export function getPublicLoanProductConfig(slug) {
  const normalized = String(slug || '').toLowerCase()
  if (normalized === 'appliance-loan') return PUBLIC_LOAN_PRODUCT_CONFIG.appliance || null
  return PUBLIC_LOAN_PRODUCT_CONFIG[normalized] || null
}
