import {
  calculatorConfigToForm,
  emptyCalculatorConfig,
  emptyRulesConfig,
  rulesConfigToForm,
} from './loanProductConfigSchema.js'

/** Quick-start templates aligned with seeded loan products. */
export const LOAN_PRODUCT_PRESETS = [
  {
    id: 'mortgage-rem',
    label: 'Real Estate Mortgage',
    short: 'REM',
    icon: 'home',
    tier: 'blue',
    form: {
      code: 'REM',
      slug: 'real-estate-mortgage',
      name: 'REM (Real Estate Mortgage)',
      collateral: 'Title',
      collateral_type: 'Real Property Title',
      interest_rate: '3.88',
      max_term: '36',
      icon_key: 'home',
    },
    calculator_config: { fee_profile: 'mortgage', computation_style: 'straight_line' },
    rules: {
      service_charge_rate: 0.035,
      insurance_per_1000: 35,
      insurance_fixed: 2000,
      doc_stamp_per_200: 1.5,
      notarial_fee_new: 1500,
      notarial_fee_reloan: 175,
      re_loan_fee: 0,
      mortgage_fee_rate: 0.02,
      mortgage_fee_threshold: 0,
    },
  },
  {
    id: 'mortgage-chm',
    label: 'Chattel Mortgage',
    short: 'CHM',
    icon: 'vehicle',
    tier: 'blue',
    form: {
      code: 'CHM',
      slug: 'chattel-mortgage',
      name: 'CHM (Chattel Mortgage)',
      collateral: 'OR/CR',
      collateral_type: 'Vehicle OR/CR',
      interest_rate: '3.88',
      max_term: '36',
      icon_key: 'vehicle',
    },
    calculator_config: { fee_profile: 'mortgage', computation_style: 'straight_line' },
    rules: {
      service_charge_rate: 0.035,
      insurance_per_1000: 35,
      insurance_fixed: 2000,
      doc_stamp_per_200: 1.5,
      notarial_fee_new: 1500,
      notarial_fee_reloan: 175,
      re_loan_fee: 0,
      mortgage_fee_rate: 0.02,
      mortgage_fee_threshold: 0,
    },
  },
  {
    id: 'salary',
    label: 'Salary Loan',
    short: 'SAL',
    icon: 'briefcase',
    tier: 'green',
    form: {
      code: 'SAL',
      slug: 'salary-loan',
      name: 'Salary Loan (Employees ACI)',
      collateral: 'Salary Deduction',
      collateral_type: 'Salary Assignment',
      interest_rate: '1.5',
      max_term: '60',
      icon_key: 'briefcase',
    },
    calculator_config: {
      salary_principal_multiplier: 6,
      fee_profile: 'salary',
      computation_style: 'straight_line',
    },
    rules: {
      service_charge_rate: 0.015,
      insurance_mode: 'percent',
      insurance_rate: 0.035,
      doc_stamp_rate_decimal: 0.0075,
      notarial_fee_new: 175,
      notarial_fee_reloan: 175,
      mortgage_fee_threshold: 999999999,
    },
  },
  {
    id: 'travel',
    label: 'Travel Assistance',
    short: 'TRV',
    icon: 'plane',
    tier: 'orange',
    form: {
      code: 'TRV',
      slug: 'travel-assistance-loan',
      name: 'Travel Assistance Loan',
      collateral: 'Landbank Account',
      collateral_type: 'Bank Account Holdout',
      interest_rate: '3.5',
      max_term: '36',
      max_amount: '500000',
      icon_key: 'plane',
    },
    calculator_config: {
      fee_profile: 'travel',
      max_principal: 500000,
      min_principal: 10000,
      opening_account_fee: 10000,
      fixed_term_months: 1,
    },
    rules: {
      service_charge_rate: 0.035,
      doc_stamp_per_200: 1.5,
      opening_account_fee: 10000,
      miscellaneous_deducted_from_proceeds: false,
    },
  },
  {
    id: 'pension',
    label: 'SSS / GSIS Pension',
    short: 'PEN',
    icon: 'shield',
    tier: 'green',
    form: {
      code: 'PEN',
      slug: 'sss-pension-loan',
      name: 'SSS/GSIS (Pensioner Loan)',
      collateral: 'ATM Card',
      collateral_type: 'Pension ATM',
      interest_rate: '2.24',
      max_term: '36',
      max_amount: '1000000',
      age_limit: '70',
      safe_age: '65',
      sample_monthly_pension: '4000',
      icon_key: 'shield',
    },
    calculator_config: {
      fee_profile: 'pension',
      pension_multiplier: 18.75,
      max_principal: 1000000,
      computation_style: 'straight_line',
    },
    rules: {
      service_charge_mode: 'fixed',
      service_charge_fixed_nw_sss: 2750,
      service_charge_fixed_nw_gsis: 2750,
      service_charge_fixed_rl_sss: 2000,
      service_charge_fixed_rl_gsis: 2000,
      insurance_per_1000: 35,
      doc_stamp_per_200: 1.5,
      notarial_fee_nw_sss: 350,
      notarial_fee_nw_gsis: 350,
      notarial_fee_rl_sss: 175,
      notarial_fee_rl_gsis: 175,
      pension_retention_threshold: 1000,
    },
  },
  {
    id: 'appliance',
    label: 'Appliance Loan',
    short: 'APL',
    icon: 'appliance',
    tier: 'orange',
    form: {
      code: 'APL',
      slug: 'appliance',
      name: 'Appliance Loan',
      collateral: 'Retail partner hold-out',
      collateral_type: 'Retail Item',
      interest_rate: '3.88',
      max_term: '24',
      downpayment: '15% of SRP',
      icon_key: 'appliance',
    },
    calculator_config: { fee_profile: 'appliance' },
    rules: {
      service_charge_rate: 0.035,
      insurance_per_1000: 35,
      insurance_fixed: 2000,
      doc_stamp_rate_decimal: 0.0075,
      notarial_fee_new: 500,
      outside_office_downpayment_rate: 0.15,
      in_office_downpayment_rate: 0,
      default_purchase_channel: 'outside_office',
    },
  },
]

export function presetToConfigState(preset) {
  const calcParsed = calculatorConfigToForm(preset.calculator_config || {})
  const rulesParsed = rulesConfigToForm(preset.rules || {})
  return {
    calculatorConfig: { ...emptyCalculatorConfig(), ...calcParsed.form },
    rulesConfig: { ...emptyRulesConfig(), ...rulesParsed.form },
    calcExtra: calcParsed.extra,
    rulesExtra: rulesParsed.extra,
  }
}

export function applyPresetToForm(currentForm, preset, mode) {
  if (mode === 'edit') {
    return {
      form: {
        ...currentForm,
        tier: preset.tier || currentForm.tier,
        icon_key: preset.form.icon_key || currentForm.icon_key,
      },
      configState: presetToConfigState(preset),
      presetId: preset.id,
    }
  }
  return {
    form: {
      ...currentForm,
      ...preset.form,
      tier: preset.tier || currentForm.tier,
      description: currentForm.description || '',
      requirements: currentForm.requirements || '',
      status: currentForm.status || 'active',
      rate_type: currentForm.rate_type || 'monthly',
      sort_order: currentForm.sort_order || '0',
    },
    configState: presetToConfigState(preset),
    presetId: preset.id,
  }
}
