/**
 * Blocks until the Amalgated Lending Laravel API responds on GET /api/v1/health.
 * Waits only on the port written by serve-laravel (.laravel-bind-port) so a stale
 * server on another port (e.g. 8010) cannot satisfy the check before the new bind.
 *
 * Writes amalgated-lending/.env.development.local so Vite's loadEnv() picks up the same
 * proxy port (avoids vite.config reading scripts/.laravel-active-port before it exists).
 */
const fs = require('fs')
const http = require('http')
const path = require('path')
const {
  writeActivePort,
  clearActivePort,
  readBindPort,
  readStartStatus,
} = require('./laravel-active-port.cjs')
const { loadDotenvLite } = require('./load-dotenv-lite.cjs')

loadDotenvLite(path.resolve(__dirname, '..', '.env'))

const host = process.env.LARAVEL_HOST || '127.0.0.1'
const timeoutMs = Number(process.env.LARAVEL_WAIT_MS || 20000)
const strictWait = String(process.env.LARAVEL_WAIT_STRICT || '').toLowerCase() === 'true'
const bootGraceMs = Number(process.env.LARAVEL_BOOT_GRACE_MS || 3000)
const intervalMs = 150

function healthOk(port) {
  return new Promise((resolve) => {
    const req = http.get(
      {
        hostname: host,
        port: parseInt(port, 10) || 8000,
        path: '/api/v1/health',
        timeout: 3000,
        headers: { Accept: 'application/json' },
      },
      (res) => {
        let body = ''
        res.on('data', (c) => {
          body += c
        })
        res.on('end', () => {
          if (res.statusCode !== 200) return resolve(false)
          try {
            const j = JSON.parse(body)
            resolve(Boolean(j && j.ok === true))
          } catch {
            resolve(false)
          }
        })
      },
    )
    req.on('error', () => resolve(false))
    req.on('timeout', () => {
      req.destroy()
      resolve(false)
    })
  })
}

async function main() {
  clearActivePort()
  const start = Date.now()
  process.stderr.write(
    `Waiting for Laravel API (GET /api/v1/health → {"ok":true}) on the port from serve-laravel …\n`,
  )
  for (;;) {
    const status = readStartStatus()
    if (status && status.state === 'failed') {
      process.stderr.write(
        `Laravel startup failed: ${status.reason || 'unknown error'}\n` +
          `  • Fix backend startup first (example: set PHP_BINARY to PHP 8.3+).\n`,
      )
      process.exit(1)
    }
    if (!status && strictWait && Date.now() - start > bootGraceMs) {
      process.stderr.write(
        `Laravel startup status not found after ${bootGraceMs}ms.\n` +
          `  • Backend likely failed before reporting a bind port.\n` +
          `  • Check "npm run serve:laravel" output first.\n`,
      )
      process.exit(1)
    }
    const bind = readBindPort()
    if (bind) {
      if (await healthOk(bind)) {
        writeActivePort(bind)
        const root = path.join(__dirname, '..')
        const envLocal = path.join(root, '.env.development.local')
        const lines = [
          '# Generated by scripts/wait-laravel.cjs — do not commit (*.local is gitignored)',
          `VITE_API_PROXY_TARGET=http://127.0.0.1:${bind}`,
          `VITE_BACKEND_PORT=${bind}`,
          '',
        ].join('\n')
        try {
          fs.writeFileSync(envLocal, lines, 'utf8')
        } catch (e) {
          process.stderr.write(`Warning: could not write .env.development.local: ${e && e.message ? e.message : e}\n`)
        }
        process.stderr.write(`Laravel API is up on port ${bind}; starting Vite.\n`)
        process.exit(0)
      }
    }
    if (Date.now() - start > timeoutMs) {
      const modeNote = strictWait
        ? 'Strict mode enabled (LARAVEL_WAIT_STRICT=true), stopping startup.'
        : 'Continuing with Vite startup (best effort mode).'
      process.stderr.write(
        `Timeout (${timeoutMs}ms).\n` +
          `  • Run from amalgated-lending: npm run serve:laravel (or npm run dev) so scripts/serve-laravel.cjs runs.\n` +
          `  • Expected scripts/.laravel-bind-port with the port php artisan serve chose.\n` +
          `  • ${modeNote}\n`,
      )
      process.exit(strictWait ? 1 : 0)
    }
    await new Promise((r) => setTimeout(r, intervalMs))
  }
}

main()
